### ISSUE TITLE
Error on windows

### ISSUE THREAD

**Issue by broerse** [ember-codemods/ember-no-implicit-this-codemod#122]
If I run `npx ember-no-implicit-this-codemod http://localhost:4200 /dev/ember-cli-blog/app/**/*.hbs` it keeps downloading chromium and other npm modules and gives me this error:

```
C:\dev\ember-no-implicit-this-codemod>npx ember-no-implicit-this-codemod http://localhost:4200 /dev/ember-cli-blog/app/**/*.hbs
Downloading Chromium r686378 - 143 Mb [====================] 100% 0.0s
(node:9532) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'C:\Users\Martin\AppData\Local\Temp\Martin\if-you-need-to-delete-this-open-an-issue-sync-disk-cache'
    at Object.mkdirSync (fs.js:757:3)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Martin\AppData\Roaming\npm-cache\_npx\9532\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:78:17)
(node:9532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It seems related to this test error:
```
C:\dev\ember-no-implicit-this-codemod>npm test

> ember-no-implicit-this-codemod@2.0.0 test C:\dev\ember-no-implicit-this-codemod
> jest

jest-haste-map: Haste module naming collision: app
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\test\fixtures\3.10\input\package.json
    * <rootDir>\test\fixtures\3.10\output\package.json

 FAIL  transforms/no-implicit-this/test.js
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at sync (node_modules/mkdirp/index.js:92:27)
      at sync (node_modules/mkdirp/index.js:77:24)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)
      at sync (node_modules/mkdirp/index.js:78:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.231s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

C:\dev\ember-no-implicit-this-codemod>
```

**Comment by broerse** [comment]
`npm run codemod /dev/ember-cli-blog/app` works.
