### ISSUE TITLE
Error Thrown during Telemetry Gathering

### ISSUE THREAD

**Issue by alexlafroscia** [ember-codemods/ember-no-implicit-this-codemod#207]
I am running into the same error as the Angle Bracket codemod when trying to run this:

https://github.com/ember-codemods/ember-angle-brackets-codemod/issues/243

<details>
  <summary>Stack Trace</summary>
  <p>

```
(node:79453) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'entries' of undefined
    at __puppeteer_evaluation_script__:9:50
    at ExecutionContext._evaluateInternal (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async gatherTelemetry (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:26:21)
    at async /Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/bin/cli.js:9:3
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/Page.js:833:43)
    at Page.<anonymous> (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/helper.js:112:23)
    at bridgeEvaluate (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:66:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async gatherTelemetry (/Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/node_modules/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js:26:21)
    at async /Users/alafroscia/.npm/_npx/79453/lib/node_modules/ember-no-implicit-this-codemod/bin/cli.js:9:3
(node:79453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:79453) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</p></details>

The result is that the codemod can't be used.

Is it possible to run this codemod without telemetry data, the same way that the Angle Bracket codemod can?

**Comment by jrjohnson** [comment]
Cross posting @rjschie's solution from the linked issue, temporarily changing my app's `targets.js` to include `last 4 Chrome versions` allowed me to run this codemod.

**Comment by yads** [comment]
Also ran into this issue because we serve on a different path, so I had to call it with `http://localhost:4200/ui/` rather than `http://localhost:4200/`.

**Comment by knownasilya** [comment]
Telemetry helpers need to be updated to 2.0 I think

**Comment by Techn1x** [comment]
Getting the same stack trace. Unfortunately the `targets.js` workaround with last 4 chrome versions didn't work, so I tried last 20 chrome versions which got past the error

**Comment by Techn1x** [comment]
Also tried the https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/258 PR that updates telemetry helpers to 2.0, and that did the trick as well. Might be good to merge it

**Comment by tylerbecks** [comment]
> Getting the same stack trace. Unfortunately the `targets.js` workaround with last 4 chrome versions didn't work, so I tried last 20 chrome versions which got past the error

This fixed it for me too! I changed `'last 2 Chrome versions',` to `'last 20 Chrome versions',` and restarted the server.
