### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kellyselden** [ember-codemods/ember-no-implicit-this-codemod#26]
I'm not sure what is causing this. It passes in Travis but fails on AppVeyor. It's running `npx ember-no-implicit-this-codemod http://localhost:4200/ app/` on CI.

```
RangeError: Maximum call stack size exceeded
    at normalizeStringWin32 (path.js:33:30)
    at Object.resolve (path.js:328:20)
    at sync (C:\Users\appveyor\AppData\Roaming\npm-cache\_npx\1512\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:68:14)
```

https://ci.appveyor.com/project/embercli/ember-cli-update/builds/26931625#L4337

**Comment by NullVoxPopuli** [comment]
Is this still an issue?

**Comment by kellyselden** [comment]
yep https://ci.appveyor.com/project/embercli/ember-cli-update/builds/28016205#L3222

**Comment by NullVoxPopuli** [comment]
I wonder if this is related to the windows issues I was having with ember-cli in general on windows the other week? I think something may be goofy with tmp files? 
On windows, I can't create new ember apps with the CLI

**Comment by kellyselden** [comment]
not sure, but none of the other codemods are having this problem.

**Comment by NullVoxPopuli** [comment]
I imagine any codemod using telemetry would have this problem?
Telemetry uses cache, and I don't think the other codemods do

**Comment by tylerturdenpants** [comment]
I think we should pull the cache from project or at least provide a switch to turn it off.  Sound like a good idea?

**Comment by NullVoxPopuli** [comment]
Yeah. We don't need it, and it only has caused problems

**Comment by tylerturdenpants** [comment]
so who is doing the work HAHAHA
