### ISSUE TITLE
Error running on macOS ARM

### ISSUE THREAD

**Issue by deanmarano** [ember-codemods/ember-no-implicit-this-codemod#395]
Hi there! I discovered this while trying to run on my M1 Pro Mac. Trying to run against a 3.28 app, but I believe this is due to an old telemetry package.

```
$ npx ember-no-implicit-this-codemod http://localhost:4200 app/**/*.hbs
The chromium binary is not available for arm64:
If you are on Ubuntu, you can install with:

 apt-get install chromium-browser

/Users/dean/.npm/_npx/92999/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
            throw new Error();
            ^

Error
    at /Users/dean/.npm/_npx/92999/lib/node_modules/ember-no-implicit-this-codemod/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
    at FSReqCallback.oncomplete (fs.js:192:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@5.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@5.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by rtablada** [comment]
I've been hitting this recently too. Is there any workaround to get a running build?

**Comment by mansona** [comment]
This has been fixed in https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/400
