### ISSUE TITLE
Tests do not pass on Windows

### ISSUE THREAD

**Issue by dustinsoftware** [ember-codemods/ember-no-implicit-this-codemod#5]
Steps to repro:

1. Clone the repo
1. Restore packages with `yarn`
1. Run `yarn test`
![image](https://user-images.githubusercontent.com/942358/61229319-fa6a9c80-a6f5-11e9-8e2b-c1b513bdbf22.png)

**Comment by kellyselden** [comment]
I'm getting this on Windows too

```
Error: EEXIST: file already exists, mkdir 'C:\Users\kelly\AppData\Local\Temp\kelly\if-you-need-to-delete-this-open-an-issue-sync-disk-cache'
    at Object.mkdirSync (fs.js:764:3)
    at sync (C:\Users\kelly\AppData\Roaming\npm-cache\_npx\4824\node_modules\ember-no-implicit-this-codemod\node_modules\mkdirp\index.js:71:13)
```

**Comment by rwjblue** [comment]
@kellyselden - were you also running the tests in this packages test suite or actually running the codemod on your app?

**Comment by kellyselden** [comment]
I was trying to get it to work in ember-cli-update, so the code looked something like this.

`cp.spawn('npx', ['ember-no-implicit-this-codemod', url, 'app/'], { shell: true });`

**Comment by NullVoxPopuli** [comment]
is this still an issue?
